name: soono
favicon: null
layout_spectrum: 0.00946
typography_spectrum: 0.7473
title: 'Soono LLC: Empowering Business'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a8ccc'
    - '#454b4f'
    - '#000000'
    - '#0000ff'
    - '#0055aa'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
